### ISSUE TITLE
强化学习

### ISSUE THREAD

**Issue by mj-0525** [Word2VecT/BUPT-Data-Structure-Practicum-2024#1]
同学你好，请问你是北邮大三的同学吗？想问问你有没有鲁鹏老师强化学习课程的资料，打扰你了。

**Comment by Word2VecT** [comment]
> 同学你好，请问你是北邮大三的同学吗？想问问你有没有鲁鹏老师强化学习课程的资料，打扰你了。

不是的学长，我是计科大二哈哈，不认识鲁鹏老师，抱歉～
